//searchProduct
const SET_VALUE = 'SET_VALUE'
const SET_RESULT = 'SET_RESULT'
//cart
const ADD_TO_CART = 'ADD_TO_CART'
const DELETE_FROM_CART = 'DELETE_FROM_CART'
const INCREMENT = 'INCREMENT'
const DECREMENT = 'DECREMENT'
const DELETE_ALL_ITEMS = 'DELETE_ALL_ITEMS'

//product
const SET_PRODUCT = 'SET_PRODUCT'
const GET_REVIEWS = 'GET_REVIEWS'
const GET_USERS = 'GET_USERS'
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
const SET_ALL_PRODUCT = 'SET_ALL_PRODUCT'
const SORT_BY = 'SORT_BY'
const SET_ASC_ORDER = 'SET_ASC_ORDER'
const SET_DESC_ORDER = 'SET_DESC_ORDER'
const SET_DESC_RATING_ORDER = 'SET_DESC_RATING_ORDER'
const SET_SEARCH_PRODUCT = 'SET_SEARCH_PRODUCT'
const GET_SOME_PRODUCT = 'GET_SOME_PRODUCT'

//utils
const TOOGLE_IS_FETCHING = 'TOOGLE_IS_FETCHING'


export {
    SET_VALUE, SET_RESULT, ADD_TO_CART, DELETE_FROM_CART, INCREMENT, DECREMENT,
    DELETE_ALL_ITEMS, SET_PRODUCT, GET_REVIEWS, GET_USERS, SET_CURRENT_PAGE, SET_ALL_PRODUCT,
    SORT_BY, SET_ASC_ORDER, SET_DESC_ORDER, SET_DESC_RATING_ORDER, SET_SEARCH_PRODUCT, GET_SOME_PRODUCT,
    TOOGLE_IS_FETCHING
}
